### ISSUE TITLE
Project blank

### ISSUE THREAD

**Issue by thesoulharmonic** [IRCSS/3D-Moebius-Transformations-Vertex-shader-in-Unity-3D#1]
I've tried to open the project and the scene but it just appears blank and the assets are missing. I'm using the same version of unity

**Comment by IRCSS** [comment]
Thanks for letting me know. The mesh folder was on gitignore, so the scene probably couldnt find it. I pushed the mesh now, pull again and let me know if it works

**Comment by thesoulharmonic** [comment]
Yes it loads now but there are no controls or moving cameras. Thank you

**Comment by thesoulharmonic** [comment]
sorry my bad yes it works perfectly now. Thank you
